### ISSUE TITLE
nrHarvestTimer does not run when instantiating from main.brs

### ISSUE THREAD

**Issue by rdobda-gaia** [newrelic/video-agent-roku#12]
We are having an issue with video-agent-roku installation on the roku client. The instructions say to create the newRelic component in main.brs. When creating the com.newrelic.NRAgent in main.brs, the nrHarvestTimer appears to not run and so events are not sent. We believe this happens because the component is being created in main.brs instead of the scene. When we move this logic into the Scene, then the timer appears to run properly and the events are sent. We believe this is an issue with the install instructions, but would like you to confirm.

**Comment by rdobda-gaia** [comment]
Also, when using this workaround, we can query RokuSystem in our New Relic instance and see several APP_STARTED events. However, we are NOT seeing any custom events (that we are sending using nrSendCustomEvent) being received in the RokuSystem table. How can we see these events?

Also, what is the preferred way to track PageView events in Roku? We are unable to see them using the customEvent, also wondering if we are doing it wrong, either in setup, config, or implementation.

**Comment by asllop** [comment]
Could you please provide more details about your implementation? The installation instructions worked well for other customers, and actually the demo app, using the same method to setup the agent, works well too (you can check it, running the demo app included in the present repository).

**Comment by rdobda-gaia** [comment]
We didn't notice there was a demo app, but anyway, in our case, we were able to get it working by moving the initialization to the roku scene, so i will close this ticket. thanks!
