### ISSUE TITLE
Instructions for "enablement" of roku dashboards include feature not available

### ISSUE THREAD

**Issue by rdobda-gaia** [newrelic/video-agent-roku#13]
There is no "import dashboard" feature available on the New relic instance so i am unable to import the JSON. I have admin on my instance, and after opening a ticket with New Relic, they are a little unclear.

**Comment by adwetzelnr** [comment]
@rdobda-gaia the [enablement readme](https://github.com/newrelic/video-agent-roku/blob/master/enablement/instruction-dashboard-json-import.md) does have a note after Step 2 that Steps 3-6 can only be performed by someone at New Relic.

If you have an account team you usually interface with you can ask them and they can help.

or...

**Comment by adwetzelnr** [comment]
@rdobda-gaia you can email me at awetzel@newrelic.com with the account id you'd like to add the dashboard to and I can do it for you.

(I'll delete this comment after you're all set)
