### ISSUE TITLE
ifDeviceInfo.getVersion() to be replaced by ifDeviceInfo.getOsVersion()

### ISSUE THREAD

**Issue by timalacey** [newrelic/video-agent-roku#27]
`ifDeviceInfo.getVersion()` on Roku OS 10 will return `999.99E99999X`
![image](https://user-images.githubusercontent.com/11152170/114327476-87b57c00-9b7c-11eb-9425-aaadbe0d68a0.png)
`ifDeviceInfo.getOsVersion()` should be used

**Comment by asllop** [comment]
Issue fixed in https://github.com/newrelic/video-agent-roku/commit/f5b65a4fc70543137bf214552d5da82df41c42a4
