### ISSUE TITLE
Dashboard JSON No Longer Valid

### ISSUE THREAD

**Issue by justinpage** [newrelic/video-agent-roku#33]
When downloading the latest available JSON from master:

https://raw.githubusercontent.com/newrelic/video-agent-roku/master/enablement/roku-dashboard.json

Results in New Relic not accepting it:
![Screen Shot 2021-08-14 at 5 27 27 PM](https://user-images.githubusercontent.com/3615935/129463344-af693fc7-d5db-4df1-b58f-dcb27210999a.png)

Looking at the JSON itself, I was able to remove the last property: `"dashboard_account_id":xxxxx`.

However, even when removing that entry, I was given the following error message on import:
```
Make sure you’re using the Dashboards Public API JSON Schema.
```

Looking at the following documentation:
https://docs.newrelic.com/docs/apis/insights-apis/insights-dashboard-api/

We can see that New Relic's Schema has recently changed when compared to what is available in the `master` branch.

@adwetzelnr / @asllop: could one of you export the dashboard again, from New Relic, and update the latest copy here?

Really appreciate the help!

**Comment by cjmccarthy** [comment]
Hey @justinpage, thanks for catching this! The PR above should fix the issue, and as a bonus I've included a nice multi-page dashboard as well with some more advanced analytics. We'll merge the PR soon, but feel free to grab the JSON from the PR in the meantime.
