### ISSUE TITLE
Crash: Uninitialized Variable

### ISSUE THREAD

**Issue by eltongouveia** [newrelic/video-agent-roku#49]
As can be seen below, a crash is happening when using a playlist. If the previous video state is `paused` and the playlist index change, it will crash due to an uninitialized variable.

![Captura de ecrã 2022-10-03, às 18 47 13](https://user-images.githubusercontent.com/52492629/193644237-f9f1d27e-0abc-458b-9d1a-f5366243b9e4.png)

**Comment by asllop** [comment]
Issue fixed in v3.1.1
