### ISSUE TITLE
splashTime attribute is recorded as a String instead of a numeric

### ISSUE THREAD

**Issue by cjmccarthy** [newrelic/video-agent-roku#51]
splashTime attribute is recorded as a String instead of a numeric

**Comment by asllop** [comment]
@cjmccarthy the `splashTime` attribute comes directly from the associative array passed to `Main` when the channel starts, we copy it as is in the `APP_STARTED` event, and it is a string in the origin. This associative array contains multiple attributes, but unfortunately they are poorly documented, so there is no way to make sure what is the purpose, meaning, and standard format of `splashTime`. For this reason, a conversion of this attribute is risky, nowhere says is will always be number, it could suddenly change the format in the next RokuOS release. The only available mentions of this attributes can be found here:

https://developer.roku.com/en-gb/docs/developer-program/discovery/implementing-deep-linking.md
https://developer.roku.com/en-gb/docs/developer-program/getting-started/architecture/dev-environment.md
