### ISSUE TITLE
IP Address

### ISSUE THREAD

**Issue by cjmccarthy** [newrelic/video-agent-roku#54]
https://github.com/newrelic/video-agent-roku/blob/3c95d8775217cd4946028a802bd3bf1dedb378ba/components/NewRelicAgent/NRAgent.brs#L714

What happens if this line is uncommented? Are there implications other than that the customer will begin collecting IP address in the logs? @asllop

**Comment by asllop** [comment]
No other implications, just commented out because of the GDPR.
